workspace(name = "test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "3ccc4e5ae8c1ce844456e39cc11f1c991a7da74396faabe83d779836ef449bce",
    urls = ["https://github.com/grpc/grpc/archive/v1.27.0.tar.gz"],
    strip_prefix = "grpc-1.27.0",
    patches = [
        "//:protobuf.patch",
        "//:python_rules.patch",
    ],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@upb//bazel:workspace_deps.bzl", "upb_deps")

upb_deps()

load("@build_bazel_rules_apple//apple:repositories.bzl", "apple_rules_dependencies")

apple_rules_dependencies()

load("@build_bazel_apple_support//lib:repositories.bzl", "apple_support_dependencies")

apple_support_dependencies()

new_local_repository(
    name = "proto_targets",
    path = "proto",
    build_file = "proto_BUILD.bazel",
)
